# Generated by Django 5.1.4 on 2024-12-17 20:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background_colour',
            field=colorfield.fields.ColorField(default='000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='text_color',
            field=colorfield.fields.ColorField(default='ffffff', image_field=None, max_length=25, samples=None),
        ),
    ]
