# Generated by Django 5.1.4 on 2024-12-18 16:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_background_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='post-image'),
        ),
    ]
