# Generated by Django 5.1.4 on 2024-12-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
