# Generated by Django 5.1.4 on 2024-12-19 16:50

import cloudinary.models
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('background_colour', colorfield.fields.ColorField(default='000000', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='ffffff', image_field=None, max_length=25, samples=None)),
                ('description', models.TextField(blank=True, help_text='Optional description of the technology.')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('background_colour', colorfield.fields.ColorField(default='000000', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='ffffff', image_field=None, max_length=25, samples=None)),
                ('short_description', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('feature_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='project-image')),
                ('meta_description', models.TextField(max_length=160)),
                ('meta_keywords', models.CharField(help_text='Comma-separated SEO keywords', max_length=255)),
                ('project_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('technologies', models.ManyToManyField(related_name='projects', to='portfolio.technology')),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
