# Generated by Django 5.1.4 on 2025-03-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='repo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
